import 'package:flutter_test/flutter_test.dart';
import 'package:reestoko/core/network/models/inventory_item_dto.dart';
import 'package:reestoko/core/network/models/shopping_item_dto.dart';

void main() {
  group('OpenAPI Models Serialization Unit Tests', () {
    test('InventoryItemDto JSON serialization & deserialization', () {
      final json = {
        'id': 'item_101',
        'name': 'Organic Milk',
        'zoneId': 'zone_fridge',
        'category': 'Dairy',
        'quantity': 2,
        'minThreshold': 1,
        'unit': 'gallon',
        'status': 'EXPIRING_SOON',
      };

      final dto = InventoryItemDto.fromJson(json);
      expect(dto.id, equals('item_101'));
      expect(dto.name, equals('Organic Milk'));
      expect(dto.quantity, equals(2));
      expect(dto.status, equals('EXPIRING_SOON'));

      final serialized = dto.toJson();
      expect(serialized['id'], equals('item_101'));
      expect(serialized['quantity'], equals(2));
    });

    test('ShoppingItemDto JSON serialization & deserialization', () {
      final json = {
        'id': 'shop_202',
        'name': 'Whole Wheat Bread',
        'quantityToBuy': 1,
        'unit': 'loaf',
        'isPurchased': false,
        'isAutoGenerated': true,
      };

      final dto = ShoppingItemDto.fromJson(json);
      expect(dto.id, equals('shop_202'));
      expect(dto.name, equals('Whole Wheat Bread'));
      expect(dto.isAutoGenerated, isTrue);
    });
  });
}
