/// **Architecture Layer**: Core / Utils
/// **Purpose**: Programmatic Firestore Data Seeder for populating demo families, users, storage zones, and groceries.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:reestoko/core/utils/app_logger.dart';

class FirebaseSeedData {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Seed demo households, storage zones, and items into Cloud Firestore
  static Future<void> seedDemoData() async {
    AppLogger.i('Starting Cloud Firestore demo data seeding...');

    try {
      final batch = _firestore.batch();

      // =======================================================================
      // 1. Household 1: Johnson Family Pantry
      // =======================================================================
      final house1Ref = _firestore.collection('households').doc('house_johnson_01');
      batch.set(house1Ref, {
        'id': 'house_johnson_01',
        'name': 'Johnson Family Pantry',
        'ownerUid': 'usr_alex_123',
        'memberUids': ['usr_alex_123'],
        'createdAt': FieldValue.serverTimestamp(),
      });

      // Zones for Household 1
      final zones1 = [
        {'id': 'zone_fridge', 'name': 'Fridge', 'iconName': 'snowflake', 'itemCount': 6},
        {'id': 'zone_pantry', 'name': 'Pantry', 'iconName': 'archive', 'itemCount': 5},
        {'id': 'zone_freezer', 'name': 'Freezer', 'iconName': 'cube', 'itemCount': 3},
      ];

      for (final zone in zones1) {
        final zoneRef = house1Ref.collection('zones').doc(zone['id'] as String);
        batch.set(zoneRef, zone);
      }

      // Grocery Items for Household 1
      final items1 = [
        {
          'id': 'item_101',
          'name': 'Organic Whole Milk 1L',
          'zoneId': 'zone_fridge',
          'category': 'Dairy',
          'quantity': 2,
          'minThreshold': 1,
          'unit': 'liter',
          'status': 'EXPIRING_SOON',
          'expirationDate': DateTime.now().add(const Duration(days: 2)).toIso8601String(),
          'barcode': '012345678905',
          'createdBy': 'usr_alex_123',
        },
        {
          'id': 'item_102',
          'name': 'Whole Wheat Loaf',
          'zoneId': 'zone_pantry',
          'category': 'Bakery',
          'quantity': 1,
          'minThreshold': 1,
          'unit': 'loaf',
          'status': 'NORMAL',
          'expirationDate': DateTime.now().add(const Duration(days: 5)).toIso8601String(),
          'barcode': '012345678906',
          'createdBy': 'usr_alex_123',
        },
        {
          'id': 'item_103',
          'name': 'Large Grade A Eggs 12ct',
          'zoneId': 'zone_fridge',
          'category': 'Dairy',
          'quantity': 1,
          'minThreshold': 1,
          'unit': 'pack',
          'status': 'LOW_STOCK',
          'expirationDate': DateTime.now().add(const Duration(days: 8)).toIso8601String(),
          'barcode': '012345678907',
          'createdBy': 'usr_alex_123',
        },
        {
          'id': 'item_104',
          'name': 'Red Bell Peppers',
          'zoneId': 'zone_fridge',
          'category': 'Produce',
          'quantity': 3,
          'minThreshold': 2,
          'unit': 'pcs',
          'status': 'NORMAL',
          'expirationDate': DateTime.now().add(const Duration(days: 6)).toIso8601String(),
          'createdBy': 'usr_alex_123',
        },
        {
          'id': 'item_105',
          'name': 'Boneless Chicken Breast',
          'zoneId': 'zone_freezer',
          'category': 'Meat',
          'quantity': 2,
          'minThreshold': 1,
          'unit': 'kg',
          'status': 'NORMAL',
          'expirationDate': DateTime.now().add(const Duration(days: 60)).toIso8601String(),
          'createdBy': 'usr_alex_123',
        },
      ];

      for (final item in items1) {
        final itemRef = house1Ref.collection('items').doc(item['id'] as String);
        item['createdAt'] = FieldValue.serverTimestamp();
        item['updatedAt'] = FieldValue.serverTimestamp();
        batch.set(itemRef, item);
      }

      // Shopping List for Household 1
      final shopItems1 = [
        {
          'id': 'shop_101',
          'name': 'Greek Yogurt 500g',
          'quantityToBuy': 2,
          'unit': 'pcs',
          'isPurchased': false,
          'isAutoGenerated': false,
          'addedBy': 'usr_alex_123',
        },
        {
          'id': 'shop_102',
          'name': 'Grade A Eggs 12ct',
          'quantityToBuy': 1,
          'unit': 'pack',
          'inventoryItemId': 'item_103',
          'isPurchased': false,
          'isAutoGenerated': true,
          'addedBy': 'usr_alex_123',
        },
      ];

      for (final shop in shopItems1) {
        final shopRef = house1Ref.collection('shopping_list').doc(shop['id'] as String);
        shop['createdAt'] = FieldValue.serverTimestamp();
        batch.set(shopRef, shop);
      }

      // Commit Batch Write
      await batch.commit();
      AppLogger.i('Cloud Firestore demo seeding complete!');
    } catch (e) {
      AppLogger.e('Error during Firestore seeding: $e');
    }
  }
}
