/// **Architecture Layer**: Presentation (Widgets)
/// **Purpose**: Reusable UI widgets for the Shopping List Screen (Shopping Card, Add Item Dialog).

import 'package:fluentui_system_icons/fluentui_system_icons.dart';
import 'package:flutter/material.dart';
import 'package:reestoko/core/network/models/shopping_item_dto.dart';

class ShoppingItemCard extends StatelessWidget {
  final ShoppingItemDto item;
  final Function(bool) onTogglePurchased;

  const ShoppingItemCard({
    super.key,
    required this.item,
    required this.onTogglePurchased,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      elevation: 1,
      child: CheckboxListTile(
        value: item.isPurchased,
        onChanged: (val) => onTogglePurchased(val ?? false),
        activeColor: Theme.of(context).primaryColor,
        checkboxShape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
        title: Text(
          item.name,
          style: TextStyle(
            fontWeight: FontWeight.bold,
            decoration: item.isPurchased ? TextDecoration.lineThrough : TextDecoration.none,
            color: item.isPurchased ? Colors.grey : Colors.black87,
          ),
        ),
        subtitle: Row(
          children: [
            Text(
              '${item.quantityToBuy} ${item.unit}',
              style: TextStyle(color: Colors.grey[600], fontSize: 12),
            ),
            if (item.isAutoGenerated) ...[
              const SizedBox(width: 8),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                decoration: BoxDecoration(
                  color: Colors.amber.withValues(alpha: 0.2),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: const Row(
                  children: [
                    Icon(FluentIcons.flash_24_filled, size: 10, color: Colors.amber),
                    SizedBox(width: 2),
                    Text(
                      'Auto Low Stock',
                      style: TextStyle(fontSize: 9, color: Colors.amber, fontWeight: FontWeight.bold),
                    ),
                  ],
                ),
              ),
            ],
          ],
        ),
        secondary: CircleAvatar(
          backgroundColor: item.isPurchased ? Colors.grey[200] : Theme.of(context).primaryColor.withValues(alpha: 0.1),
          child: Icon(
            FluentIcons.cart_24_regular,
            color: item.isPurchased ? Colors.grey : Theme.of(context).primaryColor,
          ),
        ),
      ),
    );
  }
}

class AddShoppingItemDialog extends StatefulWidget {
  final Function(ShoppingItemDto) onAdd;

  const AddShoppingItemDialog({super.key, required this.onAdd});

  @override
  State<AddShoppingItemDialog> createState() => _AddShoppingItemDialogState();
}

class _AddShoppingItemDialogState extends State<AddShoppingItemDialog> {
  final _nameController = TextEditingController();
  final _qtyController = TextEditingController(text: '1');
  String _unit = 'pcs';

  @override
  void dispose() {
    _nameController.dispose();
    _qtyController.dispose();
    super.dispose();
  }

  void _submit() {
    if (_nameController.text.trim().isEmpty) return;

    final item = ShoppingItemDto(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      name: _nameController.text.trim(),
      quantityToBuy: int.tryParse(_qtyController.text) ?? 1,
      unit: _unit,
      isPurchased: false,
      isAutoGenerated: false,
    );

    widget.onAdd(item);
    Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      title: const Text('Add Shopping Item', style: TextStyle(fontWeight: FontWeight.bold)),
      content: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          TextField(
            controller: _nameController,
            decoration: InputDecoration(
              labelText: 'Item Name',
              hintText: 'e.g., Bananas',
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
            ),
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              Expanded(
                child: TextField(
                  controller: _qtyController,
                  keyboardType: TextInputType.number,
                  decoration: InputDecoration(
                    labelText: 'Quantity',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: DropdownButtonFormField<String>(
                  initialValue: _unit,
                  decoration: InputDecoration(
                    labelText: 'Unit',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  items: ['pcs', 'kg', 'g', 'liters', 'box', 'loaf', 'pack']
                      .map((u) => DropdownMenuItem(value: u, child: Text(u)))
                      .toList(),
                  onChanged: (val) => setState(() => _unit = val!),
                ),
              ),
            ],
          ),
        ],
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: _submit,
          style: ElevatedButton.styleFrom(
            backgroundColor: Theme.of(context).primaryColor,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
          child: const Text('Add', style: TextStyle(color: Colors.white)),
        ),
      ],
    );
  }
}
