/// **Architecture Layer**: Core / Network / Models
/// **Purpose**: Data Transfer Object matching OpenAPI ShoppingItem schema.

import 'package:equatable/equatable.dart';

class ShoppingItemDto extends Equatable {
  final String id;
  final String name;
  final int quantityToBuy;
  final String unit;
  final String? inventoryItemId;
  final bool isPurchased;
  final bool isAutoGenerated;

  const ShoppingItemDto({
    required this.id,
    required this.name,
    required this.quantityToBuy,
    this.unit = 'pcs',
    this.inventoryItemId,
    this.isPurchased = false,
    this.isAutoGenerated = false,
  });

  factory ShoppingItemDto.fromJson(Map<String, dynamic> json) {
    return ShoppingItemDto(
      id: json['id'] as String,
      name: json['name'] as String,
      quantityToBuy: (json['quantityToBuy'] as num).toInt(),
      unit: json['unit'] as String? ?? 'pcs',
      inventoryItemId: json['inventoryItemId'] as String?,
      isPurchased: json['isPurchased'] as bool? ?? false,
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'quantityToBuy': quantityToBuy,
      'unit': unit,
      if (inventoryItemId != null) 'inventoryItemId': inventoryItemId,
      'isPurchased': isPurchased,
      'isAutoGenerated': isAutoGenerated,
    };
  }

  @override
  List<Object?> get props => [
        id,
        name,
        quantityToBuy,
        unit,
        inventoryItemId,
        isPurchased,
        isAutoGenerated,
      ];
}
